// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.7
//   protoc               v3.19.1
// source: src/rce/rce.proto

/* eslint-disable */
import Long = require('long')
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire'
import type { CallContext, CallOptions } from 'nice-grpc-common'

export const protobufPackage = 'rce'

export enum STATE {
  UNKNOWN = 0,
  PENDING = 1,
  RUNNING = 2,
  COMPLETE = 3,
  FAIL = 4,
  TIMEOUT = 5,
  STOPPED = 6,
  UNRECOGNIZED = -1
}

export function sTATEFromJSON(object: any): STATE {
  switch (object) {
    case 0:
    case 'UNKNOWN':
      return STATE.UNKNOWN
    case 1:
    case 'PENDING':
      return STATE.PENDING
    case 2:
    case 'RUNNING':
      return STATE.RUNNING
    case 3:
    case 'COMPLETE':
      return STATE.COMPLETE
    case 4:
    case 'FAIL':
      return STATE.FAIL
    case 5:
    case 'TIMEOUT':
      return STATE.TIMEOUT
    case 6:
    case 'STOPPED':
      return STATE.STOPPED
    case -1:
    case 'UNRECOGNIZED':
    default:
      return STATE.UNRECOGNIZED
  }
}

export function sTATEToJSON(object: STATE): string {
  switch (object) {
    case STATE.UNKNOWN:
      return 'UNKNOWN'
    case STATE.PENDING:
      return 'PENDING'
    case STATE.RUNNING:
      return 'RUNNING'
    case STATE.COMPLETE:
      return 'COMPLETE'
    case STATE.FAIL:
      return 'FAIL'
    case STATE.TIMEOUT:
      return 'TIMEOUT'
    case STATE.STOPPED:
      return 'STOPPED'
    case STATE.UNRECOGNIZED:
    default:
      return 'UNRECOGNIZED'
  }
}

export interface Empty {}

export interface Status {
  ID: string
  Name: string
  State: STATE
  PID: Long
  StartTime: Long
  StopTime: Long
  ExitCode: Long
  Args: string[]
  Stdout: string[]
  Stderr: string[]
  Error: string
}

export interface ID {
  ID: string
}

export interface Command {
  Name: string
  Arguments: string[]
}

function createBaseEmpty(): Empty {
  return {}
}

export const Empty: MessageFns<Empty> = {
  encode(_: Empty, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Empty {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseEmpty()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(_: any): Empty {
    return {}
  },

  toJSON(_: Empty): unknown {
    const obj: any = {}
    return obj
  },

  create(base?: DeepPartial<Empty>): Empty {
    return Empty.fromPartial(base ?? {})
  },
  fromPartial(_: DeepPartial<Empty>): Empty {
    const message = createBaseEmpty()
    return message
  }
}

function createBaseStatus(): Status {
  return {
    ID: '',
    Name: '',
    State: 0,
    PID: Long.ZERO,
    StartTime: Long.ZERO,
    StopTime: Long.ZERO,
    ExitCode: Long.ZERO,
    Args: [],
    Stdout: [],
    Stderr: [],
    Error: ''
  }
}

export const Status: MessageFns<Status> = {
  encode(
    message: Status,
    writer: BinaryWriter = new BinaryWriter()
  ): BinaryWriter {
    if (message.ID !== '') {
      writer.uint32(10).string(message.ID)
    }
    if (message.Name !== '') {
      writer.uint32(18).string(message.Name)
    }
    if (message.State !== 0) {
      writer.uint32(24).int32(message.State)
    }
    if (!message.PID.equals(Long.ZERO)) {
      writer.uint32(32).int64(message.PID.toString())
    }
    if (!message.StartTime.equals(Long.ZERO)) {
      writer.uint32(40).int64(message.StartTime.toString())
    }
    if (!message.StopTime.equals(Long.ZERO)) {
      writer.uint32(48).int64(message.StopTime.toString())
    }
    if (!message.ExitCode.equals(Long.ZERO)) {
      writer.uint32(56).int64(message.ExitCode.toString())
    }
    for (const v of message.Args) {
      writer.uint32(66).string(v!)
    }
    for (const v of message.Stdout) {
      writer.uint32(74).string(v!)
    }
    for (const v of message.Stderr) {
      writer.uint32(82).string(v!)
    }
    if (message.Error !== '') {
      writer.uint32(90).string(message.Error)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Status {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseStatus()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.ID = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.Name = reader.string()
          continue
        }
        case 3: {
          if (tag !== 24) {
            break
          }

          message.State = reader.int32() as any
          continue
        }
        case 4: {
          if (tag !== 32) {
            break
          }

          message.PID = Long.fromString(reader.int64().toString())
          continue
        }
        case 5: {
          if (tag !== 40) {
            break
          }

          message.StartTime = Long.fromString(reader.int64().toString())
          continue
        }
        case 6: {
          if (tag !== 48) {
            break
          }

          message.StopTime = Long.fromString(reader.int64().toString())
          continue
        }
        case 7: {
          if (tag !== 56) {
            break
          }

          message.ExitCode = Long.fromString(reader.int64().toString())
          continue
        }
        case 8: {
          if (tag !== 66) {
            break
          }

          message.Args.push(reader.string())
          continue
        }
        case 9: {
          if (tag !== 74) {
            break
          }

          message.Stdout.push(reader.string())
          continue
        }
        case 10: {
          if (tag !== 82) {
            break
          }

          message.Stderr.push(reader.string())
          continue
        }
        case 11: {
          if (tag !== 90) {
            break
          }

          message.Error = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): Status {
    return {
      ID: isSet(object.ID) ? globalThis.String(object.ID) : '',
      Name: isSet(object.Name) ? globalThis.String(object.Name) : '',
      State: isSet(object.State) ? sTATEFromJSON(object.State) : 0,
      PID: isSet(object.PID) ? Long.fromValue(object.PID) : Long.ZERO,
      StartTime: isSet(object.StartTime)
        ? Long.fromValue(object.StartTime)
        : Long.ZERO,
      StopTime: isSet(object.StopTime)
        ? Long.fromValue(object.StopTime)
        : Long.ZERO,
      ExitCode: isSet(object.ExitCode)
        ? Long.fromValue(object.ExitCode)
        : Long.ZERO,
      Args: globalThis.Array.isArray(object?.Args)
        ? object.Args.map((e: any) => globalThis.String(e))
        : [],
      Stdout: globalThis.Array.isArray(object?.Stdout)
        ? object.Stdout.map((e: any) => globalThis.String(e))
        : [],
      Stderr: globalThis.Array.isArray(object?.Stderr)
        ? object.Stderr.map((e: any) => globalThis.String(e))
        : [],
      Error: isSet(object.Error) ? globalThis.String(object.Error) : ''
    }
  },

  toJSON(message: Status): unknown {
    const obj: any = {}
    if (message.ID !== '') {
      obj.ID = message.ID
    }
    if (message.Name !== '') {
      obj.Name = message.Name
    }
    if (message.State !== 0) {
      obj.State = sTATEToJSON(message.State)
    }
    if (!message.PID.equals(Long.ZERO)) {
      obj.PID = (message.PID || Long.ZERO).toString()
    }
    if (!message.StartTime.equals(Long.ZERO)) {
      obj.StartTime = (message.StartTime || Long.ZERO).toString()
    }
    if (!message.StopTime.equals(Long.ZERO)) {
      obj.StopTime = (message.StopTime || Long.ZERO).toString()
    }
    if (!message.ExitCode.equals(Long.ZERO)) {
      obj.ExitCode = (message.ExitCode || Long.ZERO).toString()
    }
    if (message.Args?.length) {
      obj.Args = message.Args
    }
    if (message.Stdout?.length) {
      obj.Stdout = message.Stdout
    }
    if (message.Stderr?.length) {
      obj.Stderr = message.Stderr
    }
    if (message.Error !== '') {
      obj.Error = message.Error
    }
    return obj
  },

  create(base?: DeepPartial<Status>): Status {
    return Status.fromPartial(base ?? {})
  },
  fromPartial(object: DeepPartial<Status>): Status {
    const message = createBaseStatus()
    message.ID = object.ID ?? ''
    message.Name = object.Name ?? ''
    message.State = object.State ?? 0
    message.PID =
      object.PID !== undefined && object.PID !== null
        ? Long.fromValue(object.PID)
        : Long.ZERO
    message.StartTime =
      object.StartTime !== undefined && object.StartTime !== null
        ? Long.fromValue(object.StartTime)
        : Long.ZERO
    message.StopTime =
      object.StopTime !== undefined && object.StopTime !== null
        ? Long.fromValue(object.StopTime)
        : Long.ZERO
    message.ExitCode =
      object.ExitCode !== undefined && object.ExitCode !== null
        ? Long.fromValue(object.ExitCode)
        : Long.ZERO
    message.Args = object.Args?.map(e => e) || []
    message.Stdout = object.Stdout?.map(e => e) || []
    message.Stderr = object.Stderr?.map(e => e) || []
    message.Error = object.Error ?? ''
    return message
  }
}

function createBaseID(): ID {
  return { ID: '' }
}

export const ID: MessageFns<ID> = {
  encode(message: ID, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ID !== '') {
      writer.uint32(10).string(message.ID)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ID {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseID()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.ID = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): ID {
    return { ID: isSet(object.ID) ? globalThis.String(object.ID) : '' }
  },

  toJSON(message: ID): unknown {
    const obj: any = {}
    if (message.ID !== '') {
      obj.ID = message.ID
    }
    return obj
  },

  create(base?: DeepPartial<ID>): ID {
    return ID.fromPartial(base ?? {})
  },
  fromPartial(object: DeepPartial<ID>): ID {
    const message = createBaseID()
    message.ID = object.ID ?? ''
    return message
  }
}

function createBaseCommand(): Command {
  return { Name: '', Arguments: [] }
}

export const Command: MessageFns<Command> = {
  encode(
    message: Command,
    writer: BinaryWriter = new BinaryWriter()
  ): BinaryWriter {
    if (message.Name !== '') {
      writer.uint32(10).string(message.Name)
    }
    for (const v of message.Arguments) {
      writer.uint32(18).string(v!)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Command {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseCommand()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.Name = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.Arguments.push(reader.string())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): Command {
    return {
      Name: isSet(object.Name) ? globalThis.String(object.Name) : '',
      Arguments: globalThis.Array.isArray(object?.Arguments)
        ? object.Arguments.map((e: any) => globalThis.String(e))
        : []
    }
  },

  toJSON(message: Command): unknown {
    const obj: any = {}
    if (message.Name !== '') {
      obj.Name = message.Name
    }
    if (message.Arguments?.length) {
      obj.Arguments = message.Arguments
    }
    return obj
  },

  create(base?: DeepPartial<Command>): Command {
    return Command.fromPartial(base ?? {})
  },
  fromPartial(object: DeepPartial<Command>): Command {
    const message = createBaseCommand()
    message.Name = object.Name ?? ''
    message.Arguments = object.Arguments?.map(e => e) || []
    return message
  }
}

export type RCEAgentDefinition = typeof RCEAgentDefinition
export const RCEAgentDefinition = {
  name: 'RCEAgent',
  fullName: 'rce.RCEAgent',
  methods: {
    /**
     * Start a command and immediately return its ID. Be sure to call Wait or Stop
     * to reap the command, else the agent will effectively leak memory by holding
     * unreaped commands. A command is considered running until reaped.
     */
    start: {
      name: 'Start',
      requestType: Command as typeof Command,
      requestStream: false,
      responseType: ID as typeof ID,
      responseStream: false,
      options: {}
    },
    /** Wait for a command to complete or be stopped, reap it, and return its final status. */
    wait: {
      name: 'Wait',
      requestType: ID as typeof ID,
      requestStream: false,
      responseType: Status as typeof Status,
      responseStream: false,
      options: {}
    },
    /** Get the status of a command if it hasn't been reaped by calling Wait or Stop. */
    getStatus: {
      name: 'GetStatus',
      requestType: ID as typeof ID,
      requestStream: false,
      responseType: Status as typeof Status,
      responseStream: false,
      options: {}
    },
    /** Stop then reap a command by sending it a SIGTERM signal. */
    stop: {
      name: 'Stop',
      requestType: ID as typeof ID,
      requestStream: false,
      responseType: Empty as typeof Empty,
      responseStream: false,
      options: {}
    },
    /** Return a list of all running (not reaped) commands by ID. */
    running: {
      name: 'Running',
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: ID as typeof ID,
      responseStream: true,
      options: {}
    },
    /** Execute a command and stream its status. */
    exec: {
      name: 'Exec',
      requestType: Command as typeof Command,
      requestStream: false,
      responseType: Status as typeof Status,
      responseStream: true,
      options: {}
    }
  }
} as const

export interface RCEAgentServiceImplementation<CallContextExt = {}> {
  /**
   * Start a command and immediately return its ID. Be sure to call Wait or Stop
   * to reap the command, else the agent will effectively leak memory by holding
   * unreaped commands. A command is considered running until reaped.
   */
  start(
    request: Command,
    context: CallContext & CallContextExt
  ): Promise<DeepPartial<ID>>
  /** Wait for a command to complete or be stopped, reap it, and return its final status. */
  wait(
    request: ID,
    context: CallContext & CallContextExt
  ): Promise<DeepPartial<Status>>
  /** Get the status of a command if it hasn't been reaped by calling Wait or Stop. */
  getStatus(
    request: ID,
    context: CallContext & CallContextExt
  ): Promise<DeepPartial<Status>>
  /** Stop then reap a command by sending it a SIGTERM signal. */
  stop(
    request: ID,
    context: CallContext & CallContextExt
  ): Promise<DeepPartial<Empty>>
  /** Return a list of all running (not reaped) commands by ID. */
  running(
    request: Empty,
    context: CallContext & CallContextExt
  ): ServerStreamingMethodResult<DeepPartial<ID>>
  /** Execute a command and stream its status. */
  exec(
    request: Command,
    context: CallContext & CallContextExt
  ): ServerStreamingMethodResult<DeepPartial<Status>>
}

export interface RCEAgentClient<CallOptionsExt = {}> {
  /**
   * Start a command and immediately return its ID. Be sure to call Wait or Stop
   * to reap the command, else the agent will effectively leak memory by holding
   * unreaped commands. A command is considered running until reaped.
   */
  start(
    request: DeepPartial<Command>,
    options?: CallOptions & CallOptionsExt
  ): Promise<ID>
  /** Wait for a command to complete or be stopped, reap it, and return its final status. */
  wait(
    request: DeepPartial<ID>,
    options?: CallOptions & CallOptionsExt
  ): Promise<Status>
  /** Get the status of a command if it hasn't been reaped by calling Wait or Stop. */
  getStatus(
    request: DeepPartial<ID>,
    options?: CallOptions & CallOptionsExt
  ): Promise<Status>
  /** Stop then reap a command by sending it a SIGTERM signal. */
  stop(
    request: DeepPartial<ID>,
    options?: CallOptions & CallOptionsExt
  ): Promise<Empty>
  /** Return a list of all running (not reaped) commands by ID. */
  running(
    request: DeepPartial<Empty>,
    options?: CallOptions & CallOptionsExt
  ): AsyncIterable<ID>
  /** Execute a command and stream its status. */
  exec(
    request: DeepPartial<Command>,
    options?: CallOptions & CallOptionsExt
  ): AsyncIterable<Status>
}

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends Long
    ? string | number | Long
    : T extends globalThis.Array<infer U>
      ? globalThis.Array<DeepPartial<U>>
      : T extends ReadonlyArray<infer U>
        ? ReadonlyArray<DeepPartial<U>>
        : T extends {}
          ? { [K in keyof T]?: DeepPartial<T[K]> }
          : Partial<T>

function isSet(value: any): boolean {
  return value !== null && value !== undefined
}

export type ServerStreamingMethodResult<Response> = {
  [Symbol.asyncIterator](): AsyncIterator<Response, void>
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter
  decode(input: BinaryReader | Uint8Array, length?: number): T
  fromJSON(object: any): T
  toJSON(message: T): unknown
  create(base?: DeepPartial<T>): T
  fromPartial(object: DeepPartial<T>): T
}
